language: node_js
node_js:
  - '7'
  - '6'

install:
  - yarn
  - yarn compile

script:
  - yarn lint
  - yarn lint:tests
  - yarn test:travis
  - yarn report-coverage

cache:
  yarn: true
  directories:
    - node_modules
